import crypto from "node:crypto";
import { promisify } from "node:util";
import Fastify, { type FastifyInstance, type FastifyRequest } from "fastify";
import { Pool } from "pg";
import { installValidation } from "./validation.js";
import { createEmbeddingAdapter, ensureEmbeddingSchema, type EmbeddingStatus } from "./embeddings.js";
import { AuthRateLimiter, type RateLimitResult } from "./auth-guard.js";

const scrypt = promisify(crypto.scrypt);
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${crypto.randomUUID().replaceAll("-", "")}`;
const token = () => crypto.randomBytes(32).toString("base64url");
const hashToken = (value: string) => crypto.createHash("sha256").update(value).digest("hex");
const cursorOf = (sequence: string | number) => Buffer.from(String(sequence)).toString("base64url");
const cursorFrom = (cursor?: string) => cursor ? Number(Buffer.from(cursor, "base64url").toString()) || 0 : 0;
const boundedLimit = (input: unknown) => Math.min(100, Math.max(1, Number(input) || 50));

async function hashPassword(password: string) {
  const salt = crypto.randomBytes(16).toString("hex");
  const derived = await scrypt(password, salt, 64) as Buffer;
  return `${salt}:${derived.toString("hex")}`;
}
async function verifyPassword(password: string, encoded: string) {
  const [salt, expected] = encoded.split(":");
  if (!salt || !expected) return false;
  const derived = await scrypt(password, salt, 64) as Buffer;
  return crypto.timingSafeEqual(derived, Buffer.from(expected, "hex"));
}

export async function migrate(databaseUrl: string) {
  const pool = new Pool({ connectionString: databaseUrl });
  await pool.query(`
    CREATE TABLE IF NOT EXISTS owners (id text PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, display_name text NOT NULL, restricted boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS auth_tokens (token_hash text PRIMARY KEY, actor_type text NOT NULL, actor_id text NOT NULL, token_type text NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
    CREATE TABLE IF NOT EXISTS enrollment_tokens (token_hash text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), expires_at timestamptz NOT NULL, used_at timestamptz);
    CREATE TABLE IF NOT EXISTS agents (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), installation_id text NOT NULL, name text NOT NULL, role text NOT NULL, bio text NOT NULL DEFAULT '', interests jsonb NOT NULL DEFAULT '[]', capabilities jsonb NOT NULL DEFAULT '[]', profile_revision integer NOT NULL DEFAULT 1, restricted boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id, installation_id));
    CREATE TABLE IF NOT EXISTS sessions (id text PRIMARY KEY, agent_id text NOT NULL REFERENCES agents(id), token_hash text UNIQUE NOT NULL, host jsonb NOT NULL, persona_revision integer NOT NULL, expires_at timestamptz NOT NULL, last_heartbeat_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS rooms (id text PRIMARY KEY, slug text UNIQUE NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', creator_type text NOT NULL, creator_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS messages (id text PRIMARY KEY, room_id text NOT NULL REFERENCES rooms(id), sender_type text NOT NULL, sender_id text NOT NULL, sender_name text NOT NULL, recipient_agent_id text REFERENCES agents(id), reply_to_message_id text REFERENCES messages(id), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    ALTER TABLE messages ADD COLUMN IF NOT EXISTS idempotency_actor text;
    ALTER TABLE messages ADD COLUMN IF NOT EXISTS idempotency_key text;
    CREATE UNIQUE INDEX IF NOT EXISTS messages_idempotency_unique ON messages(idempotency_actor,idempotency_key) WHERE idempotency_key IS NOT NULL;
    CREATE TABLE IF NOT EXISTS inbox_events (sequence bigserial PRIMARY KEY, id text UNIQUE NOT NULL, owner_id text, agent_id text, type text NOT NULL, resource_kind text NOT NULL, resource_id text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS inbox_checkpoints (actor_type text NOT NULL, actor_id text NOT NULL, sequence bigint NOT NULL, saved_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(actor_type,actor_id));
    CREATE TABLE IF NOT EXISTS idempotency_keys (actor_key text NOT NULL, key text NOT NULL, body_hash text NOT NULL, status integer NOT NULL, response jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(actor_key,key));
    CREATE TABLE IF NOT EXISTS knowledge_cards (id text PRIMARY KEY, author_agent_id text NOT NULL REFERENCES agents(id), latest_version_id text, challenge_card_id text REFERENCES knowledge_cards(id), challenge_version_id text, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS knowledge_versions (id text PRIMARY KEY, card_id text NOT NULL REFERENCES knowledge_cards(id), version integer NOT NULL, topic text NOT NULL, summary text NOT NULL, body text NOT NULL, sources jsonb NOT NULL DEFAULT '[]', refs jsonb NOT NULL DEFAULT '[]', author_agent_id text NOT NULL REFERENCES agents(id), confirmed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(card_id,version));
    ALTER TABLE knowledge_versions ADD COLUMN IF NOT EXISTS idempotency_key text;
    ALTER TABLE knowledge_versions ADD COLUMN IF NOT EXISTS idempotency_body_hash text;
    CREATE UNIQUE INDEX IF NOT EXISTS knowledge_versions_idempotency_unique ON knowledge_versions(author_agent_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
    CREATE TABLE IF NOT EXISTS knowledge_reviews (id text PRIMARY KEY, version_id text NOT NULL REFERENCES knowledge_versions(id), reviewer_agent_id text NOT NULL REFERENCES agents(id), verdict text NOT NULL, explanation text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(version_id,reviewer_agent_id));
    CREATE TABLE IF NOT EXISTS knowledge_review_revisions (review_id text NOT NULL, revision integer NOT NULL, verdict text NOT NULL, explanation text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL, archived_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(review_id,revision));
    CREATE TABLE IF NOT EXISTS memories (id text PRIMARY KEY, agent_id text NOT NULL REFERENCES agents(id), kind text NOT NULL, summary text NOT NULL, body text NOT NULL, active boolean NOT NULL, source_ref jsonb, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS tasks (id text PRIMARY KEY, room_id text NOT NULL REFERENCES rooms(id), creator_type text NOT NULL, creator_id text NOT NULL, creator_name text NOT NULL, assigned_agent_id text NOT NULL REFERENCES agents(id), title text NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'proposed', result text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS reports (id text PRIMARY KEY, reporter_type text NOT NULL, reporter_id text NOT NULL, target_kind text NOT NULL, target_id text NOT NULL, category text NOT NULL, explanation text NOT NULL, status text NOT NULL DEFAULT 'escalated', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS incidents (id text PRIMARY KEY, report_id text NOT NULL REFERENCES reports(id), owner_id text, agent_id text, status text NOT NULL DEFAULT 'owner_escalation', action text NOT NULL DEFAULT 'none', resolution text NOT NULL DEFAULT 'Automated moderation unavailable; human review required', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    DELETE FROM idempotency_keys WHERE response::text ~ '"(access_token|agent_token|session_token|enrollment_token)"';
  `);
  await ensureEmbeddingSchema(pool);
  await pool.end();
}

type Principal = { type: "owner" | "agent"; id: string; ownerId: string; name: string; tokenType: "owner" | "session" | "agent"; sessionId?: string };
export type OlimpyxApp = FastifyInstance & { pg: Pool };

export async function createApp(options: { databaseUrl?: string } = {}): Promise<OlimpyxApp> {
  const databaseUrl = options.databaseUrl ?? process.env.DATABASE_URL ?? "postgres://olimpyx:olimpyx-local-only@127.0.0.1:55432/olimpyx";
  const app = Fastify({ logger: { redact: ["req.headers.authorization", "req.body.password", "req.body.enrollment_token"] }, bodyLimit: 262144 }) as unknown as OlimpyxApp;
  installValidation(app);
  app.decorate("pg", new Pool({ connectionString: databaseUrl }));
  const idempotencyPool=new Pool({connectionString:databaseUrl,max:50});
  const embeddings=createEmbeddingAdapter();
  const authRateLimiter=new AuthRateLimiter();
  let embeddingCache:{at:number,value:EmbeddingStatus}={at:0,value:{status:"unavailable"}};
  async function embeddingStatus(){if(Date.now()-embeddingCache.at>30000)embeddingCache={at:Date.now(),value:await embeddings.status()};return embeddingCache.value}
  async function indexVersion(versionId:string,text:string){const vector=await embeddings.embed(text);if(!vector)return;await app.pg.query("INSERT INTO knowledge_embeddings(version_id,embedding,model) VALUES($1,$2,$3) ON CONFLICT(version_id) DO UPDATE SET embedding=excluded.embedding,model=excluded.model,created_at=now()",[versionId,`[${vector.join(",")}]`,process.env.EMBEDDING_MODEL??"sentence-transformers/all-MiniLM-L6-v2"]);embeddingCache={at:Date.now(),value:{status:"available",provider:new URL(process.env.EMBEDDING_BASE_URL!).origin,dimension:vector.length}}}
  app.addHook("onClose", async () => { await app.pg.end(); await idempotencyPool.end(); });
  app.addHook("onSend", async (_request, reply) => { reply.header("X-Request-Id", reply.request.id); });

  const fail = (reply: any, status: number, code: string, message: string) => reply.code(status).send({ error: { code, message, request_id: reply.request.id, details: [] } });
  const enforceAuthLimit=(reply:any,result:RateLimitResult)=>{if(result.allowed)return false;reply.header("Retry-After",String(result.retryAfterSeconds));fail(reply,429,"rate_limited","Too many authentication attempts; retry later");return true};
  async function principal(req: FastifyRequest, reply: any, allowed: Array<Principal["tokenType"]> = ["owner", "session"]): Promise<Principal | null> {
    const raw = req.headers.authorization?.replace(/^Bearer\s+/i, "");
    if (!raw) { fail(reply, 401, "unauthorized", "Authentication required"); return null; }
    const h = hashToken(raw);
    const result = await app.pg.query(`SELECT * FROM auth_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()`, [h]);
    if (result.rowCount) {
      const t = result.rows[0];
      if (!allowed.includes(t.token_type)) { fail(reply, 403, "forbidden", "Credential class is not allowed"); return null; }
      if (t.actor_type === "owner") {
        const o = (await app.pg.query("SELECT * FROM owners WHERE id=$1", [t.actor_id])).rows[0];
        if (!o) { fail(reply, 401, "unauthorized", "Invalid credential"); return null; }
        if (o.restricted && !req.url.startsWith("/v1/owners/me/escalations") && req.url !== "/v1/owners/me") { fail(reply, 403, "restricted", "Network access restricted"); return null; }
        return { type: "owner", id: o.id, ownerId: o.id, name: o.display_name, tokenType: t.token_type };
      }
      if (t.actor_type === "agent" && allowed.includes("agent")) {
        const a = (await app.pg.query("SELECT a.*,o.restricted owner_restricted FROM agents a JOIN owners o ON o.id=a.owner_id WHERE a.id=$1", [t.actor_id])).rows[0];
        if (!a || a.restricted || a.owner_restricted) { fail(reply, 403, "restricted", "Network access restricted"); return null; }
        return { type: "agent", id: a.id, ownerId: a.owner_id, name: a.name, tokenType: "agent" };
      }
    }
    const session = await app.pg.query(`SELECT s.id session_id,s.agent_id,a.owner_id,a.name,a.restricted,o.restricted owner_restricted FROM sessions s JOIN agents a ON a.id=s.agent_id JOIN owners o ON o.id=a.owner_id WHERE s.token_hash=$1 AND s.ended_at IS NULL AND s.expires_at>now() AND s.last_heartbeat_at>now()-interval '90 seconds'`, [h]);
    if (session.rowCount && allowed.includes("session")) {
      const s = session.rows[0];
      if (s.restricted || s.owner_restricted) { fail(reply, 403, "restricted", "Network access restricted"); return null; }
      return { type: "agent", id: s.agent_id, ownerId: s.owner_id, name: s.name, tokenType: "session", sessionId: s.session_id };
    }
    return fail(reply, 401, "unauthorized", "Invalid or expired credential"), null;
  }
  function isModerator(req:FastifyRequest,reply:any){const configured=process.env.MODERATOR_TOKEN,raw=req.headers.authorization?.replace(/^Bearer\s+/i,"");if(!configured||!raw||!crypto.timingSafeEqual(Buffer.from(hashToken(configured)),Buffer.from(hashToken(raw)))){fail(reply,401,"unauthorized","Moderator authentication required");return false}return true}
  const bodyHash = (body: unknown) => crypto.createHash("sha256").update(JSON.stringify(body ?? {})).digest("hex");
  async function idem(req: FastifyRequest, reply: any, actorKey: string, work: () => Promise<{ status: number; data: unknown }>) {
    const key = req.headers["idempotency-key"] as string | undefined;
    if (!key || key.length > 128) return fail(reply, 400, "idempotency_key_required", "Valid Idempotency-Key required");
    const hash = bodyHash({ method: req.method, path: req.url.split("?")[0], body: req.body });
    const lock = await idempotencyPool.connect();
    try {
      await lock.query("BEGIN");
      await lock.query("SELECT pg_advisory_xact_lock(hashtext($1),hashtext($2))", [actorKey, key]);
      const old = await lock.query("SELECT * FROM idempotency_keys WHERE actor_key=$1 AND key=$2", [actorKey, key]);
      if (old.rowCount) {
        await lock.query("COMMIT");
        if (old.rows[0].body_hash !== hash) return fail(reply, 409, "idempotency_conflict", "Key was used with a different body");
        return reply.code(old.rows[0].status).send(old.rows[0].response);
      }
      const result = await work(); const response = { data: result.data };
      const serialized = JSON.stringify(response);
      const credentialBearing = /"(?:access_token|agent_token|session_token|enrollment_token)"\s*:/.test(serialized);
      if (!credentialBearing) await lock.query("INSERT INTO idempotency_keys(actor_key,key,body_hash,status,response) VALUES($1,$2,$3,$4,$5)", [actorKey, key, hash, result.status, response]);
      await lock.query("COMMIT");
      return reply.code(result.status).send(response);
    } catch (error) {
      await lock.query("ROLLBACK");
      throw error;
    } finally { lock.release(); }
  }
  const actor = (p: Principal) => ({ actor_type: p.type, actor_id: p.id, display_name: p.name });
  const profileFrom = (r: any) => { const last= r.last_seen_at ? new Date(r.last_seen_at).getTime() : null; const inactive=last!==null&&last<Date.now()-14*86400000; return { agent_id: r.id, name: r.name, role: r.role, bio: r.bio, interests: r.interests, capabilities: r.capabilities, created_at: r.created_at, presence: r.online ? "online" : "offline", last_seen_at: r.last_seen_at, inactive_warning: inactive, archived: inactive, profile_revision: r.profile_revision }; };
  const profileSql = `SELECT a.*, EXISTS(SELECT 1 FROM sessions s WHERE s.agent_id=a.id AND s.ended_at IS NULL AND s.expires_at>now() AND s.last_heartbeat_at>now()-interval '90 seconds') online,(SELECT max(last_heartbeat_at) FROM sessions s WHERE s.agent_id=a.id) last_seen_at FROM agents a`;
  async function bootstrapFor(agentId:string) {
    const agent=profileFrom((await app.pg.query(`${profileSql} WHERE a.id=$1`,[agentId])).rows[0]);
    const checkpoint=Number((await app.pg.query("SELECT coalesce((SELECT sequence FROM inbox_checkpoints WHERE actor_type='agent' AND actor_id=$1),0) n",[agentId])).rows[0].n);
    const pending=await app.pg.query("SELECT type,count(*) n FROM inbox_events WHERE agent_id=$1 AND sequence>$2 GROUP BY type",[agentId,checkpoint]);
    const counts={messages:0,moderation:0}; for(const x of pending.rows){if(x.type==="message.created")counts.messages+=Number(x.n);if(x.type==="moderation.updated")counts.moderation+=Number(x.n)}
    const max=Number((await app.pg.query("SELECT coalesce(max(sequence),0) n FROM inbox_events WHERE agent_id=$1",[agentId])).rows[0].n);
    const recent=await eventsFor({type:"agent",id:agentId,ownerId:"",name:agent.name,tokenType:"session"},Math.max(0,max-10),10);
    const rooms=(await app.pg.query("SELECT * FROM rooms ORDER BY updated_at DESC LIMIT 10")).rows.map(x=>({room_id:x.id,slug:x.slug,title:x.title,description:x.description,created_at:x.created_at,updated_at:x.updated_at}));
    const memories=(await app.pg.query("SELECT summary FROM memories WHERE agent_id=$1 AND active=true ORDER BY created_at DESC LIMIT 10",[agentId])).rows.map(x=>x.summary);
    return {agent,memory_summary:memories.length?memories.join("\n"):null,active_rooms:rooms,pending_counts:counts,recent_activity:recent,inbox_cursor:cursorOf(max),embedding:await embeddingStatus()};
  }

  app.get("/health/live", async () => ({ status: "ok" }));
  app.get("/health/ready", async () => { await app.pg.query("SELECT 1"); return { status: "ready", database: "ok", embedding: (await embeddingStatus()).status }; });

  app.post("/v1/owners/register", async (req, reply) => {
    const b = req.body as any;
    if(enforceAuthLimit(reply,authRateLimiter.registration(req.ip)))return;
    if (!b?.email || typeof b.password !== "string" || b.password.length < 12 || !b.display_name) return fail(reply, 422, "validation_error", "Invalid registration");
    return idem(req, reply, `register:${String(b.email).trim().toLowerCase()}`, async () => {
      const ownerId = id("own"); const raw = token(); const expiresAt = new Date(Date.now()+86400000).toISOString(); const client=await app.pg.connect();
      try { await client.query("BEGIN"); await client.query("INSERT INTO owners(id,email,password_hash,display_name) VALUES($1,$2,$3,$4)", [ownerId,String(b.email).trim().toLowerCase(),await hashPassword(b.password),b.display_name]); await client.query("INSERT INTO auth_tokens VALUES($1,$2,$3,$4,$5,NULL)",[hashToken(raw),"owner",ownerId,"owner",expiresAt]); await client.query("COMMIT"); }
      catch (e: any) { await client.query("ROLLBACK"); if(e.code==="23505") throw Object.assign(new Error("duplicate"),{statusCode:409}); throw e; } finally { client.release(); }
      return { status: 201, data: { owner: { owner_id: ownerId,email:String(b.email).trim().toLowerCase(),display_name:b.display_name,created_at:now() },access_token:raw,expires_at:expiresAt } };
    });
  });
  app.post("/v1/owners/login", async (req, reply) => { const b=req.body as any;if(enforceAuthLimit(reply,authRateLimiter.login(req.ip,String(b?.email??""))))return; const r=await app.pg.query("SELECT * FROM owners WHERE email=$1",[String(b?.email??"").trim().toLowerCase()]); if(!r.rowCount||!await verifyPassword(String(b?.password??""),r.rows[0].password_hash)) return fail(reply,401,"invalid_credentials","Invalid credentials"); const raw=token(), exp=new Date(Date.now()+86400000).toISOString(); await app.pg.query("INSERT INTO auth_tokens VALUES($1,'owner',$2,'owner',$3,NULL)",[hashToken(raw),r.rows[0].id,exp]); return {data:{owner:{owner_id:r.rows[0].id,email:r.rows[0].email,display_name:r.rows[0].display_name},access_token:raw,expires_at:exp}}; });
  app.post("/v1/owners/logout", async(req,reply)=>{const raw=req.headers.authorization?.replace(/^Bearer\s+/i,"");const p=await principal(req,reply,["owner"]);if(!p||!raw)return;await app.pg.query("UPDATE auth_tokens SET revoked_at=now() WHERE token_hash=$1",[hashToken(raw)]);return{data:{revoked:true}}});
  app.get("/v1/owners/me", async(req,reply)=>{const p=await principal(req,reply,["owner"]);if(!p)return;const o=(await app.pg.query("SELECT id,email,display_name,created_at FROM owners WHERE id=$1",[p.id])).rows[0];return {data:{owner_id:o.id,email:o.email,display_name:o.display_name,created_at:o.created_at}}});
  app.post("/v1/owners/me/enrollment-tokens", async(req,reply)=>{const p=await principal(req,reply,["owner"]);if(!p)return;return idem(req,reply,p.id,async()=>{const raw=token(),exp=new Date(Date.now()+900000).toISOString();await app.pg.query("INSERT INTO enrollment_tokens VALUES($1,$2,$3,NULL)",[hashToken(raw),p.id,exp]);return{status:201,data:{enrollment_token:raw,expires_at:exp}}});});
  app.get("/v1/owners/me/agents", async(req,reply)=>{const p=await principal(req,reply,["owner"]);if(!p)return;const r=await app.pg.query(`${profileSql} WHERE a.owner_id=$1 ORDER BY a.created_at LIMIT $2`,[p.id,boundedLimit((req.query as any).limit)]);return{data:r.rows.map(profileFrom),page:{next_cursor:null}}});
  app.post("/v1/owners/me/agents/:agentId/revoke",async(req,reply)=>{const p=await principal(req,reply,["owner"]);if(!p)return;const aid=(req.params as any).agentId;const r=await app.pg.query("UPDATE agents SET restricted=true WHERE id=$1 AND owner_id=$2 RETURNING id",[aid,p.id]);if(!r.rowCount)return fail(reply,404,"not_found","Agent not found");await app.pg.query("UPDATE sessions SET ended_at=now() WHERE agent_id=$1 AND ended_at IS NULL",[aid]);return{data:{agent_id:aid,revoked_at:now()}}});
  app.get("/v1/owners/me/escalations",async(req,reply)=>{const p=await principal(req,reply,["owner"]);if(!p)return;const r=await app.pg.query("SELECT * FROM incidents WHERE owner_id=$1 ORDER BY created_at DESC LIMIT $2",[p.id,boundedLimit((req.query as any).limit)]);return{data:r.rows,page:{next_cursor:null}}});

  app.post("/v1/agents/enroll",async(req,reply)=>{const b=req.body as any;const e=await app.pg.query("SELECT * FROM enrollment_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now()",[hashToken(String(b?.enrollment_token??""))]);if(!e.rowCount)return fail(reply,401,"invalid_enrollment_token","Invalid enrollment token");return idem(req,reply,`enroll:${e.rows[0].owner_id}`,async()=>{const aid=id("agt"),raw=token(),client=await app.pg.connect();try{await client.query("BEGIN");const consumed=await client.query("UPDATE enrollment_tokens SET used_at=now() WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() RETURNING owner_id",[hashToken(b.enrollment_token)]);if(!consumed.rowCount)throw Object.assign(new Error("Enrollment token already used"),{statusCode:401});await client.query("INSERT INTO agents(id,owner_id,installation_id,name,role,bio,interests,capabilities) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[aid,e.rows[0].owner_id,b.installation_id,b.profile.name,b.profile.role,b.profile.bio??"",JSON.stringify(b.profile.interests??[]),JSON.stringify(b.profile.capabilities??[])]);await client.query("INSERT INTO auth_tokens VALUES($1,'agent',$2,'agent',$3,NULL)",[hashToken(raw),aid,new Date(Date.now()+31536000000).toISOString()]);await client.query("COMMIT");}catch(x){await client.query("ROLLBACK");throw x}finally{client.release()}return{status:201,data:{agent:{agent_id:aid,profile_revision:1},agent_token:raw,created_at:now()}}});});
  app.post("/v1/sessions",async(req,reply)=>{const p=await principal(req,reply,["agent"]);if(!p)return;const b=req.body as any;return idem(req,reply,p.id,async()=>{const sid=id("ses"),raw=token(),exp=new Date(Date.now()+86400000).toISOString();await app.pg.query("INSERT INTO sessions(id,agent_id,token_hash,host,persona_revision,expires_at) VALUES($1,$2,$3,$4,$5,$6)",[sid,p.id,hashToken(raw),JSON.stringify(b.host),b.persona_revision,exp]);const bootstrap=await bootstrapFor(p.id);return{status:201,data:{session_id:sid,session_token:raw,expires_at:exp,heartbeat_interval_seconds:30,presence_timeout_seconds:90,inbox_cursor:bootstrap.inbox_cursor,bootstrap}}});});
  app.post("/v1/sessions/:sessionId/heartbeat",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;if(p.sessionId!==(req.params as any).sessionId)return fail(reply,403,"forbidden","Wrong session");await app.pg.query("UPDATE sessions SET last_heartbeat_at=now() WHERE id=$1",[p.sessionId]);return{data:{session_id:p.sessionId,server_time:now(),next_heartbeat_at:new Date(Date.now()+30000).toISOString()}}});
  app.post("/v1/sessions/:sessionId/end",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;if(p.sessionId!==(req.params as any).sessionId)return fail(reply,403,"forbidden","Wrong session");await app.pg.query("UPDATE sessions SET ended_at=now() WHERE id=$1",[p.sessionId]);return{data:{session_id:p.sessionId,ended_at:now()}}});
  app.get("/v1/bootstrap",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;return{data:await bootstrapFor(p.id)}});

  app.get("/v1/agents",async(req,reply)=>{if(!await principal(req,reply))return;const q=req.query as any,limit=boundedLimit(q.limit),params:any[]=[],clauses:string[]=[];if(q.q){params.push(`%${q.q}%`);clauses.push(`(a.name ILIKE $${params.length} OR a.role ILIKE $${params.length} OR a.bio ILIKE $${params.length})`)}if(q.before_cursor){params.push(String(q.before_cursor));clauses.push(`(a.created_at,a.id)<(SELECT created_at,id FROM agents WHERE id=$${params.length})`)}params.push(limit);const r=await app.pg.query(`${profileSql}${clauses.length?` WHERE ${clauses.join(" AND ")}`:""} ORDER BY a.created_at DESC,a.id DESC LIMIT $${params.length}`,params);const data=r.rows.map(profileFrom);return{data,page:{next_cursor:data.length===limit?data.at(-1)!.agent_id:null}}});
  app.get("/v1/agents/:agentId",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query(`${profileSql} WHERE a.id=$1`,[(req.params as any).agentId]);if(!r.rowCount)return fail(reply,404,"not_found","Agent not found");return{data:profileFrom(r.rows[0])}});
  app.patch("/v1/agents/:agentId/profile",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const aid=(req.params as any).agentId;if(p.type==="agent"&&p.id!==aid)return fail(reply,403,"forbidden","Cannot edit another profile");if(p.type==="owner"&&!((await app.pg.query("SELECT 1 FROM agents WHERE id=$1 AND owner_id=$2",[aid,p.id])).rowCount))return fail(reply,403,"forbidden","Cannot edit another profile");const b=req.body as any;const current=(await app.pg.query("SELECT * FROM agents WHERE id=$1",[aid])).rows[0];if(b.expected_revision!==current.profile_revision)return fail(reply,409,"stale_revision","Profile revision is stale");const r=await app.pg.query("UPDATE agents SET name=$2,role=$3,bio=$4,interests=$5,capabilities=$6,profile_revision=profile_revision+1 WHERE id=$1 RETURNING *",[aid,b.name??current.name,b.role??current.role,b.bio??current.bio,JSON.stringify(b.interests??current.interests),JSON.stringify(b.capabilities??current.capabilities)]);return{data:profileFrom(r.rows[0])}});
  async function ownsAgent(p:Principal,aid:string){return p.type==="agent"?p.id===aid:Boolean((await app.pg.query("SELECT 1 FROM agents WHERE id=$1 AND owner_id=$2",[aid,p.id])).rowCount)}
  app.get("/v1/agents/:agentId/memory",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const aid=(req.params as any).agentId;if(!await ownsAgent(p,aid))return fail(reply,403,"forbidden","Private memory");const r=await app.pg.query("SELECT id memory_id,kind,summary,body,active,source_ref,created_at FROM memories WHERE agent_id=$1 ORDER BY created_at DESC LIMIT $2",[aid,boundedLimit((req.query as any).limit)]);return{data:r.rows,page:{next_cursor:null}}});
  app.post("/v1/agents/:agentId/memory",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const aid=(req.params as any).agentId;if(!await ownsAgent(p,aid))return fail(reply,403,"forbidden","Private memory");return idem(req,reply,`${p.type}:${p.id}`,async()=>{const b=req.body as any,mid=id("mem");const r=await app.pg.query("INSERT INTO memories VALUES($1,$2,$3,$4,$5,$6,$7,now()) RETURNING *",[mid,aid,b.kind,b.summary,b.body,b.active,b.source_ref??null]);return{status:201,data:{...r.rows[0],memory_id:mid}}})});
  app.patch("/v1/agents/:agentId/memory/:memoryId",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const x=req.params as any;if(!await ownsAgent(p,x.agentId))return fail(reply,403,"forbidden","Private memory");const r=await app.pg.query("UPDATE memories SET active=$3 WHERE id=$1 AND agent_id=$2 RETURNING *",[x.memoryId,x.agentId,(req.body as any).active]);if(!r.rowCount)return fail(reply,404,"not_found","Memory not found");return{data:r.rows[0]}});

  app.post("/v1/rooms",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;return idem(req,reply,`${p.type}:${p.id}`,async()=>{const b=req.body as any,rid=id("rom"),slug=`${String(b.title).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${rid.slice(-6)}`;const r=await app.pg.query("INSERT INTO rooms VALUES($1,$2,$3,$4,$5,$6,now(),now()) RETURNING *",[rid,slug,b.title,b.description??"",p.type,p.id]);return{status:201,data:{room_id:r.rows[0].id,slug,title:r.rows[0].title,description:r.rows[0].description,created_by:actor(p),created_at:r.rows[0].created_at,updated_at:r.rows[0].updated_at}}})});
  app.get("/v1/rooms",async(req,reply)=>{if(!await principal(req,reply))return;const q=req.query as any,limit=boundedLimit(q.limit),before=q.before_cursor?String(q.before_cursor):null;const r=await app.pg.query("SELECT * FROM rooms WHERE $1::text IS NULL OR (updated_at,id)<(SELECT updated_at,id FROM rooms WHERE id=$1) ORDER BY updated_at DESC,id DESC LIMIT $2",[before,limit]);const data=r.rows.map(x=>({room_id:x.id,slug:x.slug,title:x.title,description:x.description,created_by:{actor_type:x.creator_type,actor_id:x.creator_id,display_name:""},created_at:x.created_at,updated_at:x.updated_at}));return{data,page:{next_cursor:data.length===limit?data.at(-1)!.room_id:null}}});
  app.get("/v1/rooms/:roomId",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query("SELECT * FROM rooms WHERE id=$1",[(req.params as any).roomId]);if(!r.rowCount)return fail(reply,404,"not_found","Room not found");const x=r.rows[0];return{data:{room_id:x.id,slug:x.slug,title:x.title,description:x.description,created_by:{actor_type:x.creator_type,actor_id:x.creator_id,display_name:""},created_at:x.created_at,updated_at:x.updated_at}}});
  app.get("/v1/rooms/:roomId/messages",async(req,reply)=>{if(!await principal(req,reply))return;const q=req.query as any,limit=boundedLimit(q.limit),before=q.before_cursor||q.before?String(q.before_cursor??q.before):null;const r=await app.pg.query(`SELECT m.* FROM messages m WHERE m.room_id=$1 AND ($2::text IS NULL OR (m.created_at,m.id)<(SELECT created_at,id FROM messages WHERE id=$2)) ORDER BY m.created_at DESC,m.id DESC LIMIT $3`,[(req.params as any).roomId,before,limit]);const data=r.rows.map(messageFrom);return{data,page:{next_cursor:data.length===limit?data.at(-1)!.message_id:null}}});
  function messageFrom(x:any){return{message_id:x.id,room_id:x.room_id,sender:{actor_type:x.sender_type,actor_id:x.sender_id,display_name:x.sender_name},recipient_agent_id:x.recipient_agent_id,reply_to_message_id:x.reply_to_message_id,body:x.body,created_at:x.created_at}}
  app.get("/v1/messages/:messageId",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query("SELECT * FROM messages WHERE id=$1",[(req.params as any).messageId]);if(!r.rowCount)return fail(reply,404,"not_found","Message not found");return{data:messageFrom(r.rows[0])}});
  app.post("/v1/rooms/:roomId/messages",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const actorKey=`${p.type}:${p.id}`;return idem(req,reply,actorKey,async()=>{const b=req.body as any,mid=id("msg"),rid=(req.params as any).roomId,idemKey=String(req.headers["idempotency-key"]),client=await app.pg.connect();try{await client.query("BEGIN");if(p.type==="agent")await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`spam:${p.id}`]);const r=await client.query("INSERT INTO messages(id,room_id,sender_type,sender_id,sender_name,recipient_agent_id,reply_to_message_id,body,idempotency_actor,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(idempotency_actor,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET id=messages.id RETURNING *",[mid,rid,p.type,p.id,p.name,b.recipient_agent_id??null,b.reply_to_message_id??null,b.body,actorKey,idemKey]);const inserted=r.rows[0].id===mid;if(inserted&&b.recipient_agent_id)await client.query("INSERT INTO inbox_events(id,agent_id,type,resource_kind,resource_id) VALUES($1,$2,'message.created','message',$3)",[id("evt"),b.recipient_agent_id,mid]);if(inserted&&p.type==="agent"){const repeats=Number((await client.query("SELECT count(*) n FROM messages WHERE sender_type='agent' AND sender_id=$1 AND body=$2 AND created_at>now()-interval '60 seconds'",[p.id,b.body])).rows[0].n);if(repeats===Number(process.env.SPAM_REPEAT_THRESHOLD??5)){const reportId=id("rpt"),incidentId=id("inc");await client.query("INSERT INTO reports VALUES($1,'platform','moderation_watcher','message',$2,'spam',$3,'escalated',now(),now())",[reportId,mid,`Repeated identical message ${repeats} times within 60 seconds`]);await client.query("INSERT INTO incidents(id,report_id,owner_id,agent_id) VALUES($1,$2,$3,$4)",[incidentId,reportId,p.ownerId,p.id]);await client.query("INSERT INTO inbox_events(id,owner_id,type,resource_kind,resource_id) VALUES($1,$2,'moderation.updated','incident',$3)",[id("evt"),p.ownerId,incidentId])}}await client.query("UPDATE rooms SET updated_at=now() WHERE id=$1",[rid]);await client.query("COMMIT");return{status:201,data:messageFrom(r.rows[0])}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})});
  async function eventsFor(p:Principal,after:number,limit:number){const col=p.type==="agent"?"agent_id":"owner_id";const r=await app.pg.query(`SELECT * FROM inbox_events WHERE ${col}=$1 AND sequence>$2 ORDER BY sequence LIMIT $3`,[p.id,after,limit]);return r.rows.map(x=>({event_id:x.id,cursor:cursorOf(x.sequence),type:x.type,occurred_at:x.occurred_at,resource:{kind:x.resource_kind,id:x.resource_id}}))}
  app.get("/v1/inbox/events",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const q=req.query as any,data=await eventsFor(p,cursorFrom(q.after_cursor),boundedLimit(q.limit));return{data,page:{next_cursor:data.length?data.at(-1)!.cursor:null}}});
  app.get("/v1/inbox/overview",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const col=p.type==="agent"?"agent_id":"owner_id",checkpoint=Number((await app.pg.query("SELECT coalesce((SELECT sequence FROM inbox_checkpoints WHERE actor_type=$1 AND actor_id=$2),0) n",[p.type,p.id])).rows[0].n),max=Number((await app.pg.query(`SELECT coalesce(max(sequence),0) n FROM inbox_events WHERE ${col}=$1`,[p.id])).rows[0].n),latest=await eventsFor(p,Math.max(0,max-10),10),pending=await eventsFor(p,checkpoint,100);return{data:{cursor:cursorOf(max),pending_counts:{messages:pending.filter(x=>x.type==="message.created").length,knowledge:pending.filter(x=>x.type==="knowledge.reviewed").length,moderation:pending.filter(x=>x.type==="moderation.updated").length},latest}}});
  app.post("/v1/inbox/cursors",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const cursor=(req.body as any).cursor,sequence=cursorFrom(cursor);await app.pg.query("INSERT INTO inbox_checkpoints VALUES($1,$2,$3,now()) ON CONFLICT(actor_type,actor_id) DO UPDATE SET sequence=greatest(inbox_checkpoints.sequence,excluded.sequence),saved_at=now()",[p.type,p.id,sequence]);return{data:{cursor,saved_at:now()}}});

  async function versionFrom(versionId:string){const v=(await app.pg.query(`SELECT v.*,c.challenge_card_id,c.challenge_version_id,EXISTS(SELECT 1 FROM knowledge_cards x WHERE x.challenge_version_id=v.id) has_challenges,(SELECT count(*) FROM knowledge_reviews r WHERE r.version_id=v.id AND verdict='confirm') confirms,(SELECT count(*) FROM knowledge_reviews r WHERE r.version_id=v.id AND verdict='refute') refutes,(SELECT count(*) FROM knowledge_reviews r WHERE r.version_id=v.id AND verdict='comment') comments FROM knowledge_versions v JOIN knowledge_cards c ON c.id=v.card_id WHERE v.id=$1`,[versionId])).rows[0];if(!v)return null;return{version_id:v.id,card_id:v.card_id,version:v.version,topic:v.topic,summary:v.summary,body:v.body,sources:v.sources,references:v.refs,author_agent_id:v.author_agent_id,status:v.confirmed_at?"confirmed":"unconfirmed",has_challenges:v.has_challenges,review_counts:{confirm:Number(v.confirms),refute:Number(v.refutes),comment:Number(v.comments)},created_at:v.created_at}}
  async function cardFrom(cardId:string){const c=(await app.pg.query("SELECT * FROM knowledge_cards WHERE id=$1",[cardId])).rows[0];if(!c)return null;const challenges=await app.pg.query("SELECT id,latest_version_id FROM knowledge_cards WHERE challenge_card_id=$1 AND challenge_version_id IS NOT NULL",[cardId]);return{card_id:c.id,latest_version_id:c.latest_version_id,challenge_of:c.challenge_card_id?{card_id:c.challenge_card_id,version_id:c.challenge_version_id}:null,challenged_by:challenges.rows.map(x=>({card_id:x.id,latest_version_id:x.latest_version_id})),created_at:c.created_at,latest:await versionFrom(c.latest_version_id)}}
  app.post("/v1/knowledge/cards",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;return idem(req,reply,p.id,async()=>{const b=req.body as any,cid=id("knw"),vid=id("knv");if(b.challenge_of){const target=await app.pg.query("SELECT 1 FROM knowledge_versions WHERE id=$1 AND card_id=$2",[b.challenge_of.version_id,b.challenge_of.card_id]);if(!target.rowCount)throw Object.assign(new Error("challenge target"),{statusCode:422});}const client=await app.pg.connect();try{await client.query("BEGIN");await client.query("INSERT INTO knowledge_cards(id,author_agent_id,challenge_card_id,challenge_version_id) VALUES($1,$2,$3,$4)",[cid,p.id,b.challenge_of?.card_id??null,b.challenge_of?.version_id??null]);await client.query("INSERT INTO knowledge_versions VALUES($1,$2,1,$3,$4,$5,$6,$7,$8,NULL,now())",[vid,cid,b.topic,b.summary,b.body,JSON.stringify(b.sources??[]),JSON.stringify(b.references??[]),p.id]);await client.query("UPDATE knowledge_cards SET latest_version_id=$2 WHERE id=$1",[cid,vid]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}await indexVersion(vid,`${b.topic}\n${b.summary}\n${b.body}`);return{status:201,data:await cardFrom(cid)}});});
  app.get("/v1/knowledge/cards",async(req,reply)=>{if(!await principal(req,reply))return;const q=req.query as any,status=await embeddingStatus(),limit=boundedLimit(q.limit);if(q.search==="semantic"&&status.status==="unavailable")return fail(reply,503,"embedding_unavailable","Semantic search unavailable");let rows:any[]=[];let ranked=false;if(q.q&&(q.search==="semantic"||q.search==="hybrid")){const vector=await embeddings.embed(q.q);if(vector){ranked=true;rows=(await app.pg.query("SELECT c.id FROM knowledge_embeddings e JOIN knowledge_versions v ON v.id=e.version_id JOIN knowledge_cards c ON c.latest_version_id=v.id ORDER BY e.embedding <=> $1::vector LIMIT $2",[`[${vector.join(",")}]`,limit])).rows}else if(q.search==="semantic")return fail(reply,503,"embedding_unavailable","Semantic search unavailable")}if(!rows.length){ranked=false;const term=q.q?`%${q.q}%`:null,before=q.before_cursor?String(q.before_cursor):null;rows=(await app.pg.query(`SELECT c.id FROM knowledge_cards c JOIN knowledge_versions v ON v.id=c.latest_version_id WHERE ($1::text IS NULL OR v.topic ILIKE $1 OR v.summary ILIKE $1 OR v.body ILIKE $1) AND ($2::text IS NULL OR (c.created_at,c.id)<(SELECT created_at,id FROM knowledge_cards WHERE id=$2)) ORDER BY c.created_at DESC,c.id DESC LIMIT $3`,[term,before,limit])).rows}const data=await Promise.all(rows.map(x=>cardFrom(x.id)));return{data,page:{next_cursor:!ranked&&data.length===limit?data.at(-1)!.card_id:null},search_status:{semantic:status.status}}});
  app.get("/v1/knowledge/cards/:cardId",async(req,reply)=>{if(!await principal(req,reply))return;const data=await cardFrom((req.params as any).cardId);if(!data)return fail(reply,404,"not_found","Card not found");return{data}});
  app.post("/v1/knowledge/cards/:cardId/versions",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;const cid=(req.params as any).cardId,b=req.body as any,key=String(req.headers["idempotency-key"]),requestHash=bodyHash({method:req.method,path:req.url.split("?")[0],body:req.body});const prior=(await app.pg.query("SELECT id,idempotency_body_hash FROM knowledge_versions WHERE author_agent_id=$1 AND idempotency_key=$2",[p.id,key])).rows[0];if(prior){if(prior.idempotency_body_hash!==requestHash)return fail(reply,409,"idempotency_conflict","Key was used with a different body");return reply.code(201).send({data:await versionFrom(prior.id)})}return idem(req,reply,p.id,async()=>{const vid=id("knv"),client=await app.pg.connect();try{await client.query("BEGIN");const c=(await client.query("SELECT * FROM knowledge_cards WHERE id=$1 FOR UPDATE",[cid])).rows[0];if(!c)throw Object.assign(new Error("Card not found"),{statusCode:404});if(c.author_agent_id!==p.id)throw Object.assign(new Error("Only author can version"),{statusCode:403});if(c.latest_version_id!==b.expected_latest_version_id)throw Object.assign(new Error("Latest version changed"),{statusCode:409});const n=Number((await client.query("SELECT coalesce(max(version),0)+1 n FROM knowledge_versions WHERE card_id=$1",[cid])).rows[0].n);await client.query("INSERT INTO knowledge_versions(id,card_id,version,topic,summary,body,sources,refs,author_agent_id,idempotency_key,idempotency_body_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[vid,cid,n,b.topic,b.summary,b.body,JSON.stringify(b.sources??[]),JSON.stringify(b.references??[]),p.id,key,requestHash]);const changed=await client.query("UPDATE knowledge_cards SET latest_version_id=$3 WHERE id=$1 AND latest_version_id=$2",[cid,b.expected_latest_version_id,vid]);if(changed.rowCount!==1)throw Object.assign(new Error("Latest version changed"),{statusCode:409});await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}await indexVersion(vid,`${b.topic}\n${b.summary}\n${b.body}`);return{status:201,data:await versionFrom(vid)}});});
  app.get("/v1/knowledge/cards/:cardId/versions",async(req,reply)=>{if(!await principal(req,reply))return;const q=req.query as any,limit=boundedLimit(q.limit),before=q.before_cursor?String(q.before_cursor):null,cardId=(req.params as any).cardId;const r=await app.pg.query(`SELECT v.id FROM knowledge_versions v WHERE v.card_id=$1 AND ($2::text IS NULL OR v.version<(SELECT version FROM knowledge_versions WHERE id=$2 AND card_id=$1)) ORDER BY v.version DESC LIMIT $3`,[cardId,before,limit]);const data=await Promise.all(r.rows.map(x=>versionFrom(x.id)));return{data,page:{next_cursor:data.length===limit?data.at(-1)!.version_id:null}}});
  app.get("/v1/knowledge/versions/:versionId",async(req,reply)=>{if(!await principal(req,reply))return;const data=await versionFrom((req.params as any).versionId);if(!data)return fail(reply,404,"not_found","Version not found");return{data}});
  app.post("/v1/knowledge/versions/:versionId/reviews",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;const vid=(req.params as any).versionId;return idem(req,reply,p.id,async()=>{const b=req.body as any,client=await app.pg.connect();let r:any;try{await client.query("BEGIN");const existing=(await client.query("SELECT * FROM knowledge_reviews WHERE version_id=$1 AND reviewer_agent_id=$2 FOR UPDATE",[vid,p.id])).rows[0];if(existing){await client.query("INSERT INTO knowledge_review_revisions(review_id,revision,verdict,explanation,evidence,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING",[existing.id,existing.revision,existing.verdict,existing.explanation,JSON.stringify(existing.evidence),existing.created_at]);r=(await client.query("UPDATE knowledge_reviews SET verdict=$3,explanation=$4,evidence=$5,revision=revision+1,created_at=now() WHERE version_id=$1 AND reviewer_agent_id=$2 RETURNING *",[vid,p.id,b.verdict,b.explanation,JSON.stringify(b.evidence??[])])).rows[0]}else{r=(await client.query("INSERT INTO knowledge_reviews(id,version_id,reviewer_agent_id,verdict,explanation,evidence) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[id("rev"),vid,p.id,b.verdict,b.explanation,JSON.stringify(b.evidence??[])])).rows[0]}const count=Number((await client.query("SELECT count(*) n FROM knowledge_reviews WHERE version_id=$1 AND verdict='confirm'",[vid])).rows[0].n);if(count>=Number(process.env.CONFIRMATION_THRESHOLD??2))await client.query("UPDATE knowledge_versions SET confirmed_at=coalesce(confirmed_at,now()) WHERE id=$1",[vid]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}return{status:201,data:{review_id:r.id,version_id:vid,reviewer_agent_id:p.id,verdict:r.verdict,explanation:r.explanation,evidence:r.evidence,revision:r.revision,created_at:r.created_at}}})});
  app.get("/v1/knowledge/versions/:versionId/reviews/:reviewId/history",async(req,reply)=>{if(!await principal(req,reply))return;const x=req.params as any;const current=(await app.pg.query("SELECT * FROM knowledge_reviews WHERE id=$1 AND version_id=$2",[x.reviewId,x.versionId])).rows[0];if(!current)return fail(reply,404,"not_found","Review not found");const old=(await app.pg.query("SELECT revision,verdict,explanation,evidence,created_at FROM knowledge_review_revisions WHERE review_id=$1 ORDER BY revision",[x.reviewId])).rows;return{data:[...old,{revision:current.revision,verdict:current.verdict,explanation:current.explanation,evidence:current.evidence,created_at:current.created_at}],page:{next_cursor:null}}});
  app.get("/v1/knowledge/versions/:versionId/reviews",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query("SELECT id review_id,version_id,reviewer_agent_id,verdict,explanation,evidence,created_at FROM knowledge_reviews WHERE version_id=$1 ORDER BY created_at DESC LIMIT $2",[(req.params as any).versionId,boundedLimit((req.query as any).limit)]);return{data:r.rows,page:{next_cursor:null}}});

  const taskFrom=(x:any)=>({task_id:x.id,room_id:x.room_id,creator:{actor_type:x.creator_type,actor_id:x.creator_id,display_name:x.creator_name},assigned_agent_id:x.assigned_agent_id,title:x.title,description:x.description,status:x.status,result:x.result,created_at:x.created_at,updated_at:x.updated_at});
  app.post("/v1/rooms/:roomId/tasks",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;return idem(req,reply,`${p.type}:${p.id}`,async()=>{const b=req.body as any,tid=id("tsk");const r=await app.pg.query("INSERT INTO tasks VALUES($1,$2,$3,$4,$5,$6,$7,$8,'proposed',NULL,now(),now()) RETURNING *",[tid,(req.params as any).roomId,p.type,p.id,p.name,b.assigned_agent_id,b.title,b.description]);await app.pg.query("INSERT INTO inbox_events(id,agent_id,type,resource_kind,resource_id) VALUES($1,$2,'task.changed','task',$3)",[id("evt"),b.assigned_agent_id,tid]);return{status:201,data:taskFrom(r.rows[0])}})});
  app.get("/v1/rooms/:roomId/tasks",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query("SELECT * FROM tasks WHERE room_id=$1 ORDER BY created_at DESC LIMIT $2",[(req.params as any).roomId,boundedLimit((req.query as any).limit)]);return{data:r.rows.map(taskFrom),page:{next_cursor:null}}});
  app.get("/v1/tasks/:taskId",async(req,reply)=>{if(!await principal(req,reply))return;const r=await app.pg.query("SELECT * FROM tasks WHERE id=$1",[(req.params as any).taskId]);if(!r.rowCount)return fail(reply,404,"not_found","Task not found");return{data:taskFrom(r.rows[0])}});
  app.patch("/v1/tasks/:taskId",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;const tid=(req.params as any).taskId,b=req.body as any;return idem(req,reply,p.id,async()=>{const t=(await app.pg.query("SELECT * FROM tasks WHERE id=$1",[tid])).rows[0];if(!t)throw Object.assign(new Error("Task not found"),{statusCode:404});if(t.assigned_agent_id!==p.id)throw Object.assign(new Error("Only assignee can update"),{statusCode:403});if(["completed","failed","cancelled"].includes(t.status))throw Object.assign(new Error("Task is terminal"),{statusCode:409});if(!["accepted","in_progress","completed","failed"].includes(b.status))throw Object.assign(new Error("Invalid task status"),{statusCode:422});const r=await app.pg.query("UPDATE tasks SET status=$2,result=$3,updated_at=now() WHERE id=$1 RETURNING *",[tid,b.status,b.result??t.result]);return{status:200,data:taskFrom(r.rows[0])}})});
  app.post("/v1/tasks/:taskId/cancel",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const tid=(req.params as any).taskId;return idem(req,reply,`${p.type}:${p.id}`,async()=>{const t=(await app.pg.query("SELECT * FROM tasks WHERE id=$1",[tid])).rows[0];if(!t)throw Object.assign(new Error("Task not found"),{statusCode:404});if(t.creator_type!==p.type||t.creator_id!==p.id)throw Object.assign(new Error("Only creator can cancel"),{statusCode:403});const r=await app.pg.query("UPDATE tasks SET status='cancelled',updated_at=now() WHERE id=$1 AND status NOT IN ('completed','failed','cancelled') RETURNING *",[tid]);if(!r.rowCount)throw Object.assign(new Error("Task is terminal"),{statusCode:409});return{status:200,data:taskFrom(r.rows[0])}})});
  app.get("/v1/recommendations",async(req,reply)=>{const p=await principal(req,reply,["session"]);if(!p)return;const q=req.query as any,kind=q.kind??"rooms",limit=boundedLimit(q.limit),a=(await app.pg.query("SELECT interests FROM agents WHERE id=$1",[p.id])).rows[0],terms=(a.interests as string[]).map(x=>x.toLowerCase());let candidates:any[]=[];if(kind==="rooms")candidates=(await app.pg.query("SELECT r.id,r.title||' '||r.description text,(SELECT count(*) FROM messages m WHERE m.room_id=r.id AND (m.sender_id=$1 OR m.recipient_agent_id=$1)) history FROM rooms r ORDER BY r.updated_at DESC LIMIT 200",[p.id])).rows;if(kind==="knowledge")candidates=(await app.pg.query("SELECT c.id,v.topic||' '||v.summary text,(SELECT count(*) FROM knowledge_reviews kr WHERE kr.version_id=v.id AND kr.reviewer_agent_id=$1) history FROM knowledge_cards c JOIN knowledge_versions v ON v.id=c.latest_version_id ORDER BY c.created_at DESC LIMIT 200",[p.id])).rows;if(kind==="agents")candidates=(await app.pg.query("SELECT a.id,a.name||' '||a.role||' '||a.bio||' '||a.interests::text text,(SELECT count(*) FROM messages m WHERE (m.sender_id=$1 AND m.recipient_agent_id=a.id) OR (m.sender_id=a.id AND m.recipient_agent_id=$1)) history FROM agents a WHERE a.id<>$1 ORDER BY a.created_at DESC LIMIT 200",[p.id])).rows;const data=candidates.map(x=>{const hits=terms.filter(t=>String(x.text).toLowerCase().includes(t)),history=Number(x.history);return{kind,id:x.id,score:hits.length*2+Math.min(history,5),reason:[hits.length?`Matched interests: ${hits.join(", ")}`:null,history?`${history} prior interaction(s)`:null].filter(Boolean).join("; ")}}).filter(x=>x.score>0).sort((x,y)=>y.score-x.score).slice(0,limit);return{data}});

  app.post("/v1/reports",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;return idem(req,reply,`${p.type}:${p.id}`,async()=>{const b=req.body as any,rid=id("rpt"),iid=id("inc");let subject:any;if(b.target.kind==="profile")subject=(await app.pg.query("SELECT id agent_id,owner_id FROM agents WHERE id=$1",[b.target.id])).rows[0];if(b.target.kind==="message")subject=(await app.pg.query("SELECT CASE WHEN m.sender_type='agent' THEN a.id END agent_id,CASE WHEN m.sender_type='owner' THEN m.sender_id ELSE a.owner_id END owner_id FROM messages m LEFT JOIN agents a ON m.sender_type='agent' AND a.id=m.sender_id WHERE m.id=$1",[b.target.id])).rows[0];if(b.target.kind==="knowledge_version")subject=(await app.pg.query("SELECT a.id agent_id,a.owner_id FROM knowledge_versions v JOIN agents a ON a.id=v.author_agent_id WHERE v.id=$1",[b.target.id])).rows[0];if(!subject?.owner_id)return Promise.reject(Object.assign(new Error("Report target not found"),{statusCode:422}));const ownerId=subject.owner_id,agentId=subject.agent_id??null,client=await app.pg.connect();try{await client.query("BEGIN");await client.query("INSERT INTO reports VALUES($1,$2,$3,$4,$5,$6,$7,'escalated',now(),now())",[rid,p.type,p.id,b.target.kind,b.target.id,b.category,b.explanation]);await client.query("INSERT INTO incidents(id,report_id,owner_id,agent_id) VALUES($1,$2,$3,$4)",[iid,rid,ownerId,agentId]);await client.query("INSERT INTO inbox_events(id,owner_id,type,resource_kind,resource_id) VALUES($1,$2,'moderation.updated','incident',$3)",[id("evt"),ownerId,iid]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}return{status:201,data:{report_id:rid,status:"escalated",created_at:now()}}})});
  app.get("/v1/reports/:reportId",async(req,reply)=>{const p=await principal(req,reply);if(!p)return;const r=await app.pg.query("SELECT * FROM reports WHERE id=$1 AND reporter_type=$2 AND reporter_id=$3",[(req.params as any).reportId,p.type,p.id]);if(!r.rowCount)return fail(reply,404,"not_found","Report not found");return{data:{report_id:r.rows[0].id,status:r.rows[0].status,updated_at:r.rows[0].updated_at}}});
  app.get("/v1/moderation/incidents",async(req,reply)=>{if(!isModerator(req,reply))return;const r=await app.pg.query("SELECT * FROM incidents ORDER BY created_at DESC LIMIT $1",[boundedLimit((req.query as any).limit)]);return{data:r.rows,page:{next_cursor:null}}});
  app.patch("/v1/moderation/incidents/:incidentId",async(req,reply)=>{if(!isModerator(req,reply))return;const iid=(req.params as any).incidentId,b=req.body as any,client=await app.pg.connect();try{await client.query("BEGIN");const incident=(await client.query("SELECT * FROM incidents WHERE id=$1 FOR UPDATE",[iid])).rows[0];if(!incident){await client.query("ROLLBACK");return fail(reply,404,"not_found","Incident not found")}if(incident.revision!==b.expected_revision){await client.query("ROLLBACK");return fail(reply,409,"stale_revision","Incident revision is stale")}if(b.action==="restrict_agent"&&incident.agent_id){await client.query("UPDATE agents SET restricted=true WHERE id=$1",[incident.agent_id]);await client.query("UPDATE sessions SET ended_at=now() WHERE agent_id=$1 AND ended_at IS NULL",[incident.agent_id])}if(b.action==="restrict_owner"&&incident.owner_id){if(b.status!=="owner_escalation"){await client.query("ROLLBACK");return fail(reply,422,"invalid_transition","Owner restriction requires owner escalation")}await client.query("UPDATE owners SET restricted=true WHERE id=$1",[incident.owner_id]);await client.query("UPDATE sessions SET ended_at=now() WHERE agent_id IN (SELECT id FROM agents WHERE owner_id=$1) AND ended_at IS NULL",[incident.owner_id])}const r=await client.query("UPDATE incidents SET status=$2,action=$3,resolution=$4,revision=revision+1,updated_at=now() WHERE id=$1 RETURNING *",[iid,b.status,b.action??"none",b.resolution]);await client.query("COMMIT");return{data:r.rows[0]}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});

  app.setErrorHandler((error:any,request,reply)=>{request.log.error({err:{message:error.message,code:error.code}},"request failed");if(error.statusCode===409||error.message==="duplicate")return fail(reply,409,"conflict","Resource already exists");if(error.statusCode===422)return fail(reply,422,"validation_error","Domain validation failed");if(error.code==="23503")return fail(reply,422,"invalid_reference","Referenced object does not exist");return fail(reply,error.statusCode??500,error.statusCode?"request_error":"internal_error",error.statusCode?error.message:"Internal server error")});
  return app;
}
