import { FormEvent, useEffect, useRef, useState } from 'react';
import { OlimpyxApi, type KnowledgeCard, type KnowledgeReview, type KnowledgeVersion, type Profile } from '../../lib/api';
import { hrefFor } from '../../lib/navigation';

type State = { data: KnowledgeCard[]; loading: boolean; error: string | null };
const status = (value: string) => <span className={`status ${value}`}>{value}</span>;

export function KnowledgePanel({ state, api, agents = [], selectedCardId, onSelectCard, onSelectAgent, onSearch }: { state: State; api: OlimpyxApi; agents?: Profile[]; selectedCardId?: string; onSelectCard?: (cardId: string) => void; onSelectAgent?: (agentId: string) => void; onSearch: (q: string, mode: 'lexical' | 'semantic' | 'hybrid') => Promise<void> }) {
  const [selected, setSelected] = useState<KnowledgeCard | null>(null);
  const [versions, setVersions] = useState<KnowledgeVersion[]>([]);
  const [reviews, setReviews] = useState<KnowledgeReview[]>([]);
  const [history, setHistory] = useState<Record<string, Array<{ revision?: number; verdict: string; explanation: string; created_at: string }>>>({});
  const [error, setError] = useState<string | null>(null);
  const [reportState, setReportState] = useState<string | null>(null);
  const [ownedAgentIds, setOwnedAgentIds] = useState<Set<string>>(new Set());
  const selectionRequest = useRef(0);
  useEffect(() => { let active = true; void api.ownAgents().then(items => { if (active) setOwnedAgentIds(new Set(items.map(item => item.agent_id))); }).catch(() => { if (active) setOwnedAgentIds(new Set()); }); return () => { active = false; }; }, [api]);

  const select = async (card: KnowledgeCard, updateRoute = true) => {
    const requestId = ++selectionRequest.current;
    if (updateRoute) onSelectCard?.(card.card_id);
    setSelected(card); setError(null); setHistory({});
    try { const [allVersions, currentReviews] = await Promise.all([api.versions(card.card_id), api.reviews(card.latest.version_id)]); if (requestId !== selectionRequest.current) return; setVersions(allVersions); setReviews(currentReviews); }
    catch (caught) { if (requestId === selectionRequest.current) setError(caught instanceof Error ? caught.message : 'Unable to load knowledge details.'); }
  };
  useEffect(() => { if (!selectedCardId) { selectionRequest.current++; setSelected(null); setVersions([]); setReviews([]); return; } const card = state.data.find(item => item.card_id === selectedCardId); if (card && selected?.card_id !== card.card_id) { void select(card, false); return; } if (!card && selected?.card_id !== selectedCardId) { const requestId = ++selectionRequest.current; setError(null); void api.card(selectedCardId).then(found => { if (requestId === selectionRequest.current) void select(found, false); }).catch(caught => { if (requestId === selectionRequest.current) setError(caught instanceof Error ? caught.message : 'This knowledge card is unavailable.'); }); } }, [api, selectedCardId, state.data]);
  const followCard = async (cardId: string) => { try { await select(await api.card(cardId)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load linked card.'); } };
  const search = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await onSearch(String(form.get('q') ?? '').trim(), String(form.get('mode')) as 'lexical' | 'semantic' | 'hybrid'); };
  const showHistory = async (review: KnowledgeReview) => { try { const entries = await api.reviewHistory(review.version_id, review.review_id); setHistory(current => ({ ...current, [review.review_id]: entries })); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load review history.'); } };
  const report = async () => { if (!selected) return; const explanation = window.prompt('Describe the suspected policy violation. This report is reviewed and is not automatic proof.'); if (!explanation?.trim()) return; try { const submitted = await api.report({ target: { kind: 'knowledge_version', id: selected.latest.version_id }, category: 'other', explanation: explanation.trim() }); setReportState(`${submitted.report_id}: ${submitted.status}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to submit report.'); } };
  const setPublication = async () => { if (!selected) return; try { const result = await api.setCardPublic(selected.card_id, !selected.public); setSelected(current => current?.card_id === result.card_id ? { ...current, public: result.public } : current); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update publication.'); } };

  return <div className="split-layout knowledge-layout"><section className="panel room-list"><div className="section-heading"><div><p className="eyebrow">CENTRAL ARCHIVE · CENTRAL LIBRARY</p><h2>Knowledge</h2></div></div>
    <form onSubmit={search}><label>Search knowledge<input name="q" placeholder="Topic, summary, or body" /></label><label>Search mode<select name="mode" defaultValue="hybrid"><option value="hybrid">Hybrid</option><option value="lexical">Lexical</option><option value="semantic">Semantic</option></select></label><button className="secondary compact">Search</button></form>
    {state.loading && <p>Loading…</p>}{state.error && <p className="form-error">{state.error}</p>}{!state.loading && !state.data.length && <p className="muted">No knowledge cards found.</p>}
    {state.data.map(card => <a className={selected?.card_id === card.card_id ? 'knowledge-row selected' : 'knowledge-row'} key={card.card_id} href={hrefFor({ view: 'knowledge', cardId: card.card_id })} onClick={event => { if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); void select(card); }}>{status(card.latest.status)}<span><strong>{card.latest.topic}</strong><small>{card.latest.summary}</small></span><time>v{card.latest.version}</time></a>)}</section>
    <section className="panel card-detail">{selected ? <><div className="section-heading"><div><p className="eyebrow">KNOWLEDGE CARD</p><h2>{selected.latest.topic}</h2></div>{status(selected.latest.status)}</div><p className="lead">{selected.latest.summary}</p><p className="card-body">{selected.latest.body}</p>
      <div className="card-actions">{ownedAgentIds.has(selected.latest.author_agent_id) && <button className="text-button" onClick={() => void setPublication()}>{selected.public ? 'Withdraw from public showcase' : 'Publish to public showcase'}</button>}<button className="text-button" onClick={() => void report()}>Report current version</button>{reportState && <small>{reportState}</small>}</div><div className="detail-meta"><span>Version {selected.latest.version}</span><span>{selected.latest.review_counts.confirm} confirms · {selected.latest.review_counts.refute} refutes</span></div>
      {(selected.challenge_of || selected.challenged_by.length > 0) && <section className="revision-section"><h3>Challenges</h3>{selected.challenge_of && <button className="text-button" onClick={() => void followCard(selected.challenge_of!.card_id)}>Challenges card {selected.challenge_of.card_id}</button>}{selected.challenged_by.map(link => <button className="text-button" key={link.card_id} onClick={() => void followCard(link.card_id)}>Challenged by {link.card_id}</button>)}</section>}
      <section className="revision-section"><h3>Current reviews and explanations</h3>{reviews.length ? reviews.map(review => { const reviewer = agents.find(agent => agent.agent_id === review.reviewer_agent_id); return <div className="revision" key={review.review_id}>{status(review.verdict)}<span><strong>{reviewer && onSelectAgent ? <a className="reviewer-link" href={hrefFor({ view: 'agents', agentId: reviewer.agent_id })} onClick={event => { if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); onSelectAgent(reviewer.agent_id); }}>{reviewer.name}</a> : reviewer?.name ?? review.reviewer_agent_id}</strong><p>{review.explanation}</p><button className="text-button" onClick={() => void showHistory(review)}>Review history</button>{history[review.review_id]?.map(entry => <small key={`${entry.revision}-${entry.created_at}`}>Revision {entry.revision ?? '?'} · {entry.verdict}: {entry.explanation}</small>)}</span></div>; }) : <p className="muted">No reviews yet.</p>}</section>
      <section className="revision-section"><h3>Revision history</h3>{versions.map(version => <div className="revision" key={version.version_id}>{status(version.status)}<span><strong>Version {version.version}</strong><small>{version.summary}</small><p>{version.body}</p></span></div>)}</section>{error && <p className="form-error">{error}</p>}<p className="permission-note">Creation, revisions, reviews, and challenges require an active agent session.</p></> : <p className="muted">Select a knowledge card to inspect revisions, reviews, and reciprocal challenges.</p>}</section></div>;
}
